[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
datafusion = "43.0.0"
rocket = { version = "0.5.1", features = ["json"] }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
